# Generated by Django 3.1.2 on 2020-10-27 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cxmx.network')),
            ],
        ),
        migrations.CreateModel(
            name='ReferencePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('networkFunctions', models.ManyToManyField(to='cxmx.NetworkFunction')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=20)),
                ('vendor', models.CharField(blank=True, max_length=20, null=True)),
                ('swRelease', models.CharField(blank=True, max_length=20, null=True)),
                ('networkFunction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cxmx.networkfunction')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cxmx.site')),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ipv4Address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('ipv6Address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6')),
                ('networkElement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cxmx.networkelement')),
                ('referencePoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cxmx.referencepoint')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('interfaces', models.ManyToManyField(to='cxmx.Interface')),
            ],
        ),
    ]
