# Generated by Django 3.1.2 on 2020-11-23 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cxmx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='netName', to='cxmx.network'),
        ),
    ]
