# Generated by Django 3.1.2 on 2020-11-28 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cxmx', '0002_auto_20201123_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkelement',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_name', to='cxmx.site'),
        ),
    ]
