# Generated by Django 3.1.2 on 2020-12-11 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cxmx', '0003_auto_20201128_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkelement',
            name='site',
        ),
        migrations.AlterField(
            model_name='interface',
            name='networkElement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interfaces', to='cxmx.networkelement'),
        ),
        migrations.AlterField(
            model_name='networkelement',
            name='networkFunction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='networkFunction_name', to='cxmx.networkfunction'),
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('clusterType', models.CharField(choices=[('TC', 'Telco Cloud'), ('ITC', 'IT Cloud'), ('PNFC', 'PNF Cluster')], default='TC', max_length=4)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clusters', to='cxmx.site')),
            ],
        ),
        migrations.AddField(
            model_name='networkelement',
            name='cluster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='neList', to='cxmx.cluster'),
            preserve_default=False,
        ),
    ]
