# Generated by Django 3.1.2 on 2020-12-19 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cxmx', '0006_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Erstellt am')),
                ('lastmodified_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Zuletzt geändert am')),
                ('tile', models.TextField(max_length=100)),
                ('comment', models.TextField()),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='cxmx.site')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_sitecomments_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('lastmodified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_sitecomments_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Zuletzt geändert von')),
            ],
            options={
                'ordering': ['lastmodified_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
