# Generated by Django 3.1.2 on 2020-12-20 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cxmx', '0008_auto_20201220_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitecomment',
            old_name='tile',
            new_name='title',
        ),
    ]
