# Generated by Django 3.1.2 on 2020-12-20 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cxmx', '0009_auto_20201220_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='sitecomment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_sitecomment_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='sitecomment',
            name='lastmodified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at'),
        ),
        migrations.AlterField(
            model_name='sitecomment',
            name='lastmodified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_sitecomment_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
    ]
