# Generated by Django 3.1.2 on 2020-12-23 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cxmx', '0012_auto_20201220_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clustercomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='necomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sitecomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='network',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='networkelement',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='networkfunction',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='referencepoint',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='site',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='cluster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_cluster_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='lastmodified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='lastmodified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_cluster_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DRAFT-A', 'DraftApproved'), ('DEPLOYED', 'Deployed'), ('IN-SERVICE', 'InService'), ('OUT-OF-SERVICE', 'OutOfService')], default='DRAFT', max_length=14),
        ),
        migrations.AddField(
            model_name='connection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_connection_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='connection',
            name='lastmodified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at'),
        ),
        migrations.AddField(
            model_name='connection',
            name='lastmodified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_connection_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='connection',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DRAFT-A', 'DraftApproved'), ('DEPLOYED', 'Deployed'), ('IN-SERVICE', 'InService'), ('OUT-OF-SERVICE', 'OutOfService')], default='DRAFT', max_length=14),
        ),
        migrations.AddField(
            model_name='interface',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_interface_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='interface',
            name='lastmodified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at'),
        ),
        migrations.AddField(
            model_name='interface',
            name='lastmodified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_interface_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='interface',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DRAFT-A', 'DraftApproved'), ('DEPLOYED', 'Deployed'), ('IN-SERVICE', 'InService'), ('OUT-OF-SERVICE', 'OutOfService')], default='DRAFT', max_length=14),
        ),
        migrations.AddField(
            model_name='network',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_network_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='network',
            name='lastmodified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at'),
        ),
        migrations.AddField(
            model_name='network',
            name='lastmodified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_network_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='network',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DRAFT-A', 'DraftApproved'), ('DEPLOYED', 'Deployed'), ('IN-SERVICE', 'InService'), ('OUT-OF-SERVICE', 'OutOfService')], default='DRAFT', max_length=14),
        ),
        migrations.AddField(
            model_name='networkelement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_networkelement_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='networkelement',
            name='lastmodified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at'),
        ),
        migrations.AddField(
            model_name='networkelement',
            name='lastmodified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_networkelement_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='networkelement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DRAFT-A', 'DraftApproved'), ('DEPLOYED', 'Deployed'), ('IN-SERVICE', 'InService'), ('OUT-OF-SERVICE', 'OutOfService')], default='DRAFT', max_length=14),
        ),
        migrations.AddField(
            model_name='networkfunction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_networkfunction_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='networkfunction',
            name='lastmodified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at'),
        ),
        migrations.AddField(
            model_name='networkfunction',
            name='lastmodified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_networkfunction_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='referencepoint',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_referencepoint_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='referencepoint',
            name='lastmodified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at'),
        ),
        migrations.AddField(
            model_name='referencepoint',
            name='lastmodified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_referencepoint_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='site',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_site_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='site',
            name='lastmodified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at'),
        ),
        migrations.AddField(
            model_name='site',
            name='lastmodified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_site_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DRAFT-A', 'DraftApproved'), ('DEPLOYED', 'Deployed'), ('IN-SERVICE', 'InService'), ('OUT-OF-SERVICE', 'OutOfService')], default='DRAFT', max_length=14),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='clustercomment',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clustercomments', to='cxmx.cluster'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='interface',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='necomment',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='necomments', to='cxmx.networkelement'),
        ),
        migrations.AlterField(
            model_name='network',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='networkelement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='networkelement',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='networkfunction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='referencepoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='site',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='sitecomment',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sitecomments', to='cxmx.site'),
        ),
    ]
