# Generated by Django 3.1.2 on 2020-12-24 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cxmx', '0014_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkelement',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_neList', to='cxmx.cluster'),
            preserve_default=False,
        ),
    ]
