# Generated by Django 3.1.2 on 2020-12-24 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cxmx', '0015_networkelement_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkelement',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clusterNEList', to='cxmx.cluster'),
        ),
        migrations.AlterField(
            model_name='networkelement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenantNEList', to='cxmx.tenant'),
        ),
    ]
