# Generated by Django 3.1.2 on 2020-12-25 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cxmx', '0016_auto_20201224_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('lastmodified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('name', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DRAFT-A', 'DraftApproved'), ('DEPLOYED', 'Deployed'), ('IN-SERVICE', 'InService'), ('OUT-OF-SERVICE', 'OutOfService')], default='DRAFT', max_length=14)),
                ('type', models.CharField(choices=[('L3', 'VRF'), ('L2', 'R-VPLS')], default='L3', max_length=2)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_domain_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastmodified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_domain_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('lastmodified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('name', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DRAFT-A', 'DraftApproved'), ('DEPLOYED', 'Deployed'), ('IN-SERVICE', 'InService'), ('OUT-OF-SERVICE', 'OutOfService')], default='DRAFT', max_length=14)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_zone_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('domain', models.ForeignKey(limit_choices_to={'type': 'L3'}, on_delete=django.db.models.deletion.PROTECT, related_name='domainZones', to='cxmx.domain')),
                ('lastmodified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_zone_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('lastmodified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('name', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DRAFT-A', 'DraftApproved'), ('DEPLOYED', 'Deployed'), ('IN-SERVICE', 'InService'), ('OUT-OF-SERVICE', 'OutOfService')], default='DRAFT', max_length=14)),
                ('ipV4Net', netfields.fields.CidrAddressField(max_length=43)),
                ('ipv6Net', netfields.fields.CidrAddressField(max_length=43)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_subnet_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zoneSubnets', to='cxmx.zone')),
                ('lastmodified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_subnet_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
