# Generated by Django 3.1.2 on 2020-12-26 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cxmx', '0017_domain_subnet_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnet',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zoneSubnets', to='cxmx.zone'),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='domainSubnets', to='cxmx.domain'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subnet',
            name='ipv6Net',
            field=netfields.fields.CidrAddressField(blank=True, max_length=43, null=True),
        ),
        migrations.CreateModel(
            name='Net',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('lastmodified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('name', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DRAFT-A', 'DraftApproved'), ('DEPLOYED', 'Deployed'), ('IN-SERVICE', 'InService'), ('OUT-OF-SERVICE', 'OutOfService')], default='DRAFT', max_length=14)),
                ('type', models.CharField(choices=[('LOCAL', 'Local'), ('VLAN', 'VLAN')], default='LOCAL', max_length=5)),
                ('providerPhysicalNetwork', models.CharField(blank=True, max_length=40, null=True)),
                ('providerSegementID', models.CharField(blank=True, max_length=40, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_net_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastmodified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_net_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenantNetworks', to='cxmx.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
