# Generated by Django 3.1.2 on 2020-12-26 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cxmx', '0018_auto_20201226_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnet',
            name='net',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='netSubnets', to='cxmx.net'),
            preserve_default=False,
        ),
    ]
