# Generated by Django 3.1.2 on 2020-12-26 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cxmx', '0019_subnet_net'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='subnet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='subnetInterfaces', to='cxmx.subnet'),
            preserve_default=False,
        ),
    ]
