# Generated by Django 3.1.2 on 2021-01-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxmx', '0021_subnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnet',
            name='dhcp',
            field=models.BooleanField(default=False),
        ),
    ]
