# Generated by Django 3.1.2 on 2021-01-03 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cxmx', '0024_auto_20210103_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='net',
            name='tenant',
        ),
        migrations.AddField(
            model_name='subnet',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tenantNetworks', to='cxmx.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subnet',
            name='net',
            field=models.ForeignKey(default=1, help_text='Network', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='netSubnets', to='cxmx.net', verbose_name='Network'),
        ),
    ]
