# Generated by Django 3.1.2 on 2021-01-04 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cxmx', '0025_auto_20210103_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubnetComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('lastmodified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('title', models.TextField(max_length=100)),
                ('comment', models.TextField()),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subnetComments', to='cxmx.subnet')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_subnetcomment_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastmodified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxmx_subnetcomment_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
